Web/Backend/Django/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

Web/Backend/Django/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/create', views.comment_create, name='comment_create'),
    path('<int:pk>/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

Web/Backend/Django/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import change_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', change_password, name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/Backend/Django/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

Web/Backend/Django/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')

Web/Backend/Django/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required

def index(request: HttpRequest):
    users = get_user_model().objects.all()
    context = {
        'users': users
    }
    return render(request, 'accounts/index.html', context)

def login(request: HttpRequest):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('accounts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

@login_required(login_url='accounts:login')
def logout(request: HttpRequest):
    auth_logout(request)
    return redirect('accounts:index')

def signup(request: HttpRequest):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm()   
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

@login_required(login_url='accounts:login')
def delete(request: HttpRequest):
    request.user.delete()
    auth_logout(request)
    return redirect('accounts:index')

@login_required(login_url='accounts:login')
def update(request: HttpRequest):   
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

@login_required(login_url='accounts:login')
def change_password(request: HttpRequest, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # 비밀번호 변경 후 세션 연장
            return redirect('accounts:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/change_password.html', context)

Web/Backend/Django/accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
    <h1>비밀번호 변경</h1>
    <form action="{% url "change_password" user.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">제출</button>
    </form>
{% endblock %}

Web/Backend/Django/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원 목록</h1>
  {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    <a href="{% url 'accounts:update' %}">회원정보 수정</a>
    <a href="{% url 'change_password' request.user.pk %}">비밀번호 변경</a>
    <a href="{% url 'accounts:delete' %}">회원탈퇴</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
  {% endif %}
  <ul>
    {% for user in users %}
      <li>{{ user.username }}<hr></li>
    {% endfor %}
  </ul>
{% endblock %}

Web/Backend/Django/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>로그인</h1>
  <form action="{% url 'articles:index' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
  </form>
</body>
</html>

Web/Backend/Django/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
    <h1>회원가입</h1>
    <form action="{% url "accounts:signup" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">회원가입</button> 
    </form>
{% endblock %}

Web/Backend/Django/accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
    <h1>회원정보 수정</h1>
    <form action="{% url "accounts:update" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">제출</button>
    </form>
{% endblock %}