Web/Backend/Django/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

Web/Backend/Django/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/create', views.comment_create, name='comment_create'),
    path('<int:pk>/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

Web/Backend/Django/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import change_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', change_password, name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/Backend/Django/articles/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Web/Backend/Django/articles/forms.py
from django import forms
from .models import Article, Comment

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=20)
#     content = forms.CharField()

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content',)
        # exclude = ('user')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

Web/Backend/Django/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.views.decorators.http import require_http_methods, require_GET, require_POST, require_safe

@require_safe
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

@require_safe
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)

@login_required
@require_http_methods(['GET, POST'])
def create(request: HttpRequest):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article:Article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)

@login_required
@require_POST
def delete(request: HttpRequest, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')

@login_required
@require_http_methods(['GET, POST'])
def update(request: HttpRequest, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)

@login_required
@require_POST
def comment_create(request: HttpRequest, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid:
            comment: Comment = form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
    return redirect('articles:detail', pk)

@login_required
@require_POST
def comment_delete(request: HttpRequest, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if comment.user == request.user:
        comment.delete()
    return redirect('articles:detail', article_pk)

Web/Backend/Django/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" />
  </form>
  <hr />
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}

Web/Backend/Django/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h2>{{ article.pk }} 번째 글</h2>
  <hr />
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성일 : {{ article.created_at }}</p>
  <p>수정일 : {{ article.updated_at }}</p>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="img" />
  {% endif %}
  <hr />
  {% if request.user == article.user %}
    <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제" />
    </form>
  {% endif %}
  <a href="{% url 'articles:index' %}">[back]</a>
  <form action="{% url "articles:comment_create" article.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="작성">
  </form>
  {% for comment in comments %}
    <p>{{ comment.user }} - {{ comment.content }}</p>
  {% endfor %}
{% endblock %}

Web/Backend/Django/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'articles/style.css' %}" />
{% endblock %}

{% block content %}
  {% if request.user.is_authenticated %}
  <h3>Hello, {{ request.user.username }}</h3>
  <form action="{% url 'accounts:logout' %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="LOGOUT">
  </form>
  {% else %}
  <a href="{% url 'accounts:login' %}">LOGIN</a>
  {% endif %}
  <h1>Articles</h1>
  {% comment %} <img src="{% static 'articles/sample-1.png' %}" width="200" height="200" alt="img" />
  <img src="{% static 'sample-2.png' %}" width="200" height="200" alt="img2" /> {% endcomment %}
  <a href="{% url 'articles:create' %}">CREATE</a>
  <hr />
  {% for article in articles %}
    <p>작성자: {{ article.user }}</p>
    <p>글 번호: {{ article.pk }}</p>
    <a href="{% url 'articles:detail' article.pk %}"><p>글 제목: {{ article.title }}</p></a>
    <p>글 내용: {{ article.content }}</p>
    <hr />
  {% endfor %}
{% endblock %}

Web/Backend/Django/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" />
  </form>
  <hr />
  <a href="{% url 'articles:detail' article.pk %}">[back]</a>
{% endblock %}